---
apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  keyPath: /var/db
  replicas: 1
  image: "docker.io/sarroutbi/ubi_tang_server"
  version: "clean_exit"
