build_root:
  image_stream_tag:
    cluster: https://api.ci-ln-j27509k-f76d1.origin-ci-int-gce.dev.openshift.com:6443
    namespace: openshift
    tag: golang-1.12
tests:
- as: unit
  commands: make test
  container:
    from: src
resources:
  default:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  '*':
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
