#!/bin/sh -eu
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2020 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
# Author: Sergio Arroutbi <sarroutb@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
export running=1

finish() {
    echo "captured signal, exiting ..."
    export running=0
}
trap finish INT TERM

export PORT="${PORT:-80}"

DB=/var/db/tang
TANGD=/usr/libexec/tangd

socat -v tcp-l:"${PORT}",reuseaddr,fork exec:"${TANGD} ${DB}" &
while [ ${running} -eq 1 ];
do
    sleep 0.1
done

echo "stopping tangd ..."
kill -9 "$(pgrep [s]ocat | awk '{print $2}')" 2>/dev/null
kill -9 "$(pgrep [t]angd-entrypoint | awk '{print $2}')" 2>/dev/null
