#!/bin/sh -eu
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2020 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

export PORT="${PORT:-80}"

die() {
    echo "${0}: ${1} (port: ${PORT})" >&2
    exit 1
}

# Get the advertisement.
jws="$(curl -sfg "http://localhost:${PORT}/adv")" \
       || die "Error downloading advertisement"

# Sanity check the advertisement.
jwks="$(jose fmt --json="${jws}" --object --get payload --string \
        --b64load --object --get keys --array --unwind --output=-)" \
        || die "Advertisement is malformed"

# Check validity.
printf %s "${jwks}" \
    | jose jwk use --input=- --required --use=verify --output=/dev/null \
    || die "Advertisement is missing signatures"

# Check for key derivation key.
enc="$(printf %s "${jwks}" \
       | jose jwk use --input=- --required --use=deriveKey --output=-)" \
       || die "Key derivation key not available"

# Check for exchange keys.
jose fmt --json "${enc}" --object --get keys --array \
    || enc="$(printf {keys: [%s]} "${enc}")"
#jose fmt --json="${enc}" --object --get keys --array --foreach=/dev/null \
#    || die "No exchange keys found"

echo "ok"
