---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: tang-operator
  namespace: openshift-marketplace
spec:
  displayName: "Red Hat"
  publisher: "Red Hat"
  sourceType: grpc
  image: quay.io/sec-eng-special/tang-operator-index:VERSION_HERE
