---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/tang-operator.openshift-operators: ""
  name: tang-operator
  namespace: openshift-operators
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: tang-operator
  source: tang-operator
  sourceNamespace: openshift-marketplace
