#!/bin/bash
#
# Copyright (c) 2021 Red Hat, Inc.
# Author: Sergio Arroutbi <sarroutb@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
TANG_DIRECTORY_BUILD=/root/tang/build

function usage() {
  echo "$1 -d tang-source-code-build-directory"
  return $2
}

while getopts "d:h" arg
do
  case "${arg}" in
    d) TANG_DIRECTORY_BUILD=${OPTARG}
       ;;
    h) usage $0 0
       exit 0
       ;;
  esac
done

cd $TANG_DIRECTORY_BUILD && meson test
if [ $? -eq 0 ]; then
   touch ${TANG_DIRECTORY_BUILD}/TEST_OK
else
   touch ${TANG_DIRECTORY_BUILD}/TEST_FAIL
fi

# Make container to stay running in case necessary debugging is required
tail -f /dev/null
