---
name: "Cross compilation"

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '.wordlist.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '.wordlist.txt'

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Arch: [386, arm, amd64, arm64, mips, mipsle, mips64, mips64le, ppc64, ppc64le, riscv64, s390x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Go-Setup
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.7'

    - name: Build
      env:
        GOARCH: ${{matrix.Arch}}
      run: |
        V=1 TANG_OPERATOR_CI=1 GOOS=$(go env GOOS) GOARCH=$GOARCH GOPATH=$(go env GOPATH) make build
