---
name: "Default compilation, tests and deploy"

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4.0.1
      with:
        go-version: 1.20.4

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Minikube Installation
      id: minikube
      uses: medyagh/setup-minikube@latest

    - name: Status
      run: minikube status

    #- name: Cluster Test
    #  run: CLUSTER_TANG_OPERATOR_TEST=1 make test

    - name: Deploy and Scorecard
      run: |
        sh .github/workflows/scripts/retrieve_and_run_operator_sdk.sh \
          "v1.31.0" "5m" "quay.io/sec-eng-special/tang-operator-bundle" \
          "${GITHUB_HEAD_REF}"
