---
name: "Default compilation, tests and deploy"

"on":
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '.wordlist.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '.wordlist.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Build
        run: make build

      - name: Test
        run: make test

        #      - name: Podman install
        #run: |
        #  sudo apt-get update -y
        #  sudo apt-get install -y podman
        #
      - name: Minikube Installation
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          cache: false

      - name: Status
        run: minikube status

      - name: Cluster Test
        run: CLUSTER_TANG_OPERATOR_TEST=1 make test

      - name: Deploy and Scorecard
        run: |
          sh .github/workflows/scripts/retrieve_and_run_operator_sdk \
            "v1.36.0" "5m" "quay.io/sec-eng-special/tang-operator-bundle" \
            "${GITHUB_HEAD_REF}"
